#!/bin/sh
SYNC_BRANCH=${CENTRAL_BRANCH:-upstream/master}

function localBranches() {
  git branch | sed -e s/\*//g | tr -s " " | cut -d " " -f 2 | sort
}

function remoteBranches() {
  git branch -r | grep origin | grep -v HEAD | sed -e s/origin\\///g | \
      tr -s " " | cut -d " " -f 2 | sort
}

function localStatus() {
  BEHIND=$(git log --no-merges $1..${SYNC_BRANCH} --pretty=oneline | wc -l)
  AHEAD=$(git log --no-merges ${SYNC_BRANCH}..$1 --pretty=oneline | wc -l)
  printf "%-30s ${TEXT_GREEN}%5d ${TEXT_RED}%5d${RESET_FORMATTING}\n" $1 $AHEAD $BEHIND
}
export -f localStatus

function remoteStatus() {
  BEHIND=$(git log --no-merges origin/$1..${SYNC_BRANCH} --pretty=oneline | wc -l)
  AHEAD=$(git log --no-merges ${SYNC_BRANCH}..origin/$1 --pretty=oneline | wc -l)
  printf "%-30s ${TEXT_GREEN}%5d ${TEXT_RED}%5d${RESET_FORMATTING}\n" $1 $AHEAD $BEHIND
}
export -f remoteStatus

function dualStatus() {
  BEHIND_SYNC=$(git log --no-merges $1..${SYNC_BRANCH} --pretty=oneline | wc -l)
  AHEAD_SYNC=$(git log --no-merges ${SYNC_BRANCH}..$1 --pretty=oneline | wc -l)
  BEHIND_ORIGIN=$(git log --no-merges $1..origin/$1 --pretty=oneline | wc -l)
  AHEAD_ORIGIN=$(git log --no-merges origin/$1..$1 --pretty=oneline | wc -l)
  if [ $AHEAD_SYNC = 0 ]; then
    if [ $1 != master ]; then
      COMMENT="git branch -D $1; git push origin :$1"
    fi
  fi
  printf "%-30s ${TEXT_GREEN}%5d ${TEXT_RED}%5d %10s${TEXT_GREEN}%5d ${TEXT_RED}%5d${RESET_FORMATTING}      %s\n" \
      $1 $AHEAD_ORIGIN $BEHIND_ORIGIN "" $AHEAD_SYNC $BEHIND_SYNC "$COMMENT"
}
export -f dualStatus

localBranches > /tmp/$$.local.tmp
remoteBranches > /tmp/$$.remote.tmp
comm -12 /tmp/$$.local.tmp /tmp/$$.remote.tmp > /tmp/$$.both.tmp
comm -13 /tmp/$$.local.tmp /tmp/$$.remote.tmp > /tmp/$$.remoteonly.tmp
comm -23 /tmp/$$.local.tmp /tmp/$$.remote.tmp > /tmp/$$.localonly.tmp


echo "${TEXT_RED}Local Only Branches${RESET_FORMATTING} vs ${SYNC_BRANCH}"
cat /tmp/$$.localonly.tmp | xargs -n 1 -I {} bash -c 'localStatus "$@"' _ {}
echo ""

echo "${TEXT_RED}Remote Only Branches${RESET_FORMATTING} vs ${SYNC_BRANCH}"
cat /tmp/$$.remoteonly.tmp | xargs -n 1 -I {} bash -c 'remoteStatus "$@"' _ {}
echo ""

echo "${TEXT_GREEN}Synced Branches${RESET_FORMATTING} vs origin and ${SYNC_BRANCH}"
cat /tmp/$$.both.tmp | xargs -n 1 -I {} bash -c 'dualStatus "$@"' _ {}
echo ""

rm /tmp/$$.*.tmp
